In [2]:
#program to perform svd using python
import numpy as np
from scipy.linalg import svd

m=np.array([[1,2],[3,4]])
print("matrix is :\n",m)
a,b,c=svd(m)
print("\n svd of the matrix is")
print("\n m*m : \n",a)
print("\n m*n : \n",b)
print("\n n*n : \n",c)
print("\n reconstruction of old matrix")
print(a @ np.diag(b) @c)

matrix is :
 [[1 2]
 [3 4]]

 svd of the matrix is

 m*m : 
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]

 m*n : 
 [5.4649857  0.36596619]

 n*n : 
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]

 reconstruction of old matrix
[[1. 2.]
 [3. 4.]]
