In [2]:
#program to perform matrix multiplication

import numpy as np

m1=np.array([[1,2],[3,4]])
m2=np.array([[2,4],[1,4]])
d=np.dot(m1,m2)
print("matrix m1 :\n",m1)
print("\n matrix m2 :\n",m2)
print("\n multiplication of m1 and m2 is :\n",d)

matrix m1 :
 [[1 2]
 [3 4]]

 matrix m2 :
 [[2 4]
 [1 4]]

 multiplication of m1 and m2 is :
 [[ 4 12]
 [10 28]]
